// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.7
// source: api/requestEth/v1/transaction.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReservesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair string `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
}

func (x *GetReservesRequest) Reset() {
	*x = GetReservesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReservesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservesRequest) ProtoMessage() {}

func (x *GetReservesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservesRequest.ProtoReflect.Descriptor instead.
func (*GetReservesRequest) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *GetReservesRequest) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

type GetReservesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReservesOne string `protobuf:"bytes,1,opt,name=reservesOne,proto3" json:"reservesOne,omitempty"`
	ReservesTwo string `protobuf:"bytes,2,opt,name=reservesTwo,proto3" json:"reservesTwo,omitempty"`
}

func (x *GetReservesReply) Reset() {
	*x = GetReservesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReservesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservesReply) ProtoMessage() {}

func (x *GetReservesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservesReply.ProtoReflect.Descriptor instead.
func (*GetReservesReply) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *GetReservesReply) GetReservesOne() string {
	if x != nil {
		return x.ReservesOne
	}
	return ""
}

func (x *GetReservesReply) GetReservesTwo() string {
	if x != nil {
		return x.ReservesTwo
	}
	return ""
}

type GetAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetAllReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	One           string `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`                     // usdt额度，铸造
	Two           string `protobuf:"bytes,2,opt,name=two,proto3" json:"two,omitempty"`                     // aicat总铸造数量，铸造
	Three         string `protobuf:"bytes,3,opt,name=three,proto3" json:"three,omitempty"`                 // 添加流动性usdt额度
	Four          string `protobuf:"bytes,4,opt,name=four,proto3" json:"four,omitempty"`                   // 添加流动性aicat额度
	LpAmount      string `protobuf:"bytes,5,opt,name=lpAmount,proto3" json:"lpAmount,omitempty"`           // 地址持有lp
	LpAmountTotal string `protobuf:"bytes,6,opt,name=lpAmountTotal,proto3" json:"lpAmountTotal,omitempty"` // 全局持有lp
	OneLength     string `protobuf:"bytes,7,opt,name=oneLength,proto3" json:"oneLength,omitempty"`         // 铸造使用u，记录数组当前长度
	TwoLength     string `protobuf:"bytes,8,opt,name=twoLength,proto3" json:"twoLength,omitempty"`         // 铸造产生b，记录数组当前长度
	ThreeLength   string `protobuf:"bytes,9,opt,name=threeLength,proto3" json:"threeLength,omitempty"`     // 流动性u使用记录，负数是添加，正数是移除
	FourLength    string `protobuf:"bytes,10,opt,name=fourLength,proto3" json:"fourLength,omitempty"`      // 流动性b使用记录，负数是添加，正数是移除
}

func (x *GetAllReply) Reset() {
	*x = GetAllReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReply) ProtoMessage() {}

func (x *GetAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReply.ProtoReflect.Descriptor instead.
func (*GetAllReply) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllReply) GetOne() string {
	if x != nil {
		return x.One
	}
	return ""
}

func (x *GetAllReply) GetTwo() string {
	if x != nil {
		return x.Two
	}
	return ""
}

func (x *GetAllReply) GetThree() string {
	if x != nil {
		return x.Three
	}
	return ""
}

func (x *GetAllReply) GetFour() string {
	if x != nil {
		return x.Four
	}
	return ""
}

func (x *GetAllReply) GetLpAmount() string {
	if x != nil {
		return x.LpAmount
	}
	return ""
}

func (x *GetAllReply) GetLpAmountTotal() string {
	if x != nil {
		return x.LpAmountTotal
	}
	return ""
}

func (x *GetAllReply) GetOneLength() string {
	if x != nil {
		return x.OneLength
	}
	return ""
}

func (x *GetAllReply) GetTwoLength() string {
	if x != nil {
		return x.TwoLength
	}
	return ""
}

func (x *GetAllReply) GetThreeLength() string {
	if x != nil {
		return x.ThreeLength
	}
	return ""
}

func (x *GetAllReply) GetFourLength() string {
	if x != nil {
		return x.FourLength
	}
	return ""
}

type PushOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendBody *PushOneRequest_SendBody `protobuf:"bytes,1,opt,name=send_body,json=sendBody,proto3" json:"send_body,omitempty"`
}

func (x *PushOneRequest) Reset() {
	*x = PushOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOneRequest) ProtoMessage() {}

func (x *PushOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOneRequest.ProtoReflect.Descriptor instead.
func (*PushOneRequest) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *PushOneRequest) GetSendBody() *PushOneRequest_SendBody {
	if x != nil {
		return x.SendBody
	}
	return nil
}

type PushOneReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res string `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *PushOneReply) Reset() {
	*x = PushOneReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushOneReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOneReply) ProtoMessage() {}

func (x *PushOneReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOneReply.ProtoReflect.Descriptor instead.
func (*PushOneReply) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *PushOneReply) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

type PushThreeFourRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendBody *PushThreeFourRequest_SendBody `protobuf:"bytes,1,opt,name=send_body,json=sendBody,proto3" json:"send_body,omitempty"`
}

func (x *PushThreeFourRequest) Reset() {
	*x = PushThreeFourRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushThreeFourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushThreeFourRequest) ProtoMessage() {}

func (x *PushThreeFourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushThreeFourRequest.ProtoReflect.Descriptor instead.
func (*PushThreeFourRequest) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *PushThreeFourRequest) GetSendBody() *PushThreeFourRequest_SendBody {
	if x != nil {
		return x.SendBody
	}
	return nil
}

type PushThreeFourReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res string `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *PushThreeFourReply) Reset() {
	*x = PushThreeFourReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushThreeFourReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushThreeFourReply) ProtoMessage() {}

func (x *PushThreeFourReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushThreeFourReply.ProtoReflect.Descriptor instead.
func (*PushThreeFourReply) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *PushThreeFourReply) GetRes() string {
	if x != nil {
		return x.Res
	}
	return ""
}

type VerifySigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sign    string `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *VerifySigRequest) Reset() {
	*x = VerifySigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifySigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySigRequest) ProtoMessage() {}

func (x *VerifySigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySigRequest.ProtoReflect.Descriptor instead.
func (*VerifySigRequest) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *VerifySigRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *VerifySigRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type VerifySigReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res     bool   `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *VerifySigReply) Reset() {
	*x = VerifySigReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifySigReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifySigReply) ProtoMessage() {}

func (x *VerifySigReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifySigReply.ProtoReflect.Descriptor instead.
func (*VerifySigReply) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *VerifySigReply) GetRes() bool {
	if x != nil {
		return x.Res
	}
	return false
}

func (x *VerifySigReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TokenBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token   string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *TokenBalanceRequest) Reset() {
	*x = TokenBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenBalanceRequest) ProtoMessage() {}

func (x *TokenBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenBalanceRequest.ProtoReflect.Descriptor instead.
func (*TokenBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *TokenBalanceRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TokenBalanceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance string `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Err     string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *TokenBalanceReply) Reset() {
	*x = TokenBalanceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenBalanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenBalanceReply) ProtoMessage() {}

func (x *TokenBalanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenBalanceReply.ProtoReflect.Descriptor instead.
func (*TokenBalanceReply) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *TokenBalanceReply) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *TokenBalanceReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type SendTransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendBody *SendTransactionRequest_SendBody `protobuf:"bytes,1,opt,name=send_body,json=sendBody,proto3" json:"send_body,omitempty"`
}

func (x *SendTransactionRequest) Reset() {
	*x = SendTransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionRequest) ProtoMessage() {}

func (x *SendTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionRequest.ProtoReflect.Descriptor instead.
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{12}
}

func (x *SendTransactionRequest) GetSendBody() *SendTransactionRequest_SendBody {
	if x != nil {
		return x.SendBody
	}
	return nil
}

type SendTransactionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx  string `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *SendTransactionReply) Reset() {
	*x = SendTransactionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionReply) ProtoMessage() {}

func (x *SendTransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionReply.ProtoReflect.Descriptor instead.
func (*SendTransactionReply) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{13}
}

func (x *SendTransactionReply) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

func (x *SendTransactionReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type SendTransactionEthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendBody *SendTransactionEthRequest_SendBody `protobuf:"bytes,1,opt,name=send_body,json=sendBody,proto3" json:"send_body,omitempty"`
}

func (x *SendTransactionEthRequest) Reset() {
	*x = SendTransactionEthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTransactionEthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionEthRequest) ProtoMessage() {}

func (x *SendTransactionEthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionEthRequest.ProtoReflect.Descriptor instead.
func (*SendTransactionEthRequest) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{14}
}

func (x *SendTransactionEthRequest) GetSendBody() *SendTransactionEthRequest_SendBody {
	if x != nil {
		return x.SendBody
	}
	return nil
}

type SendTransactionEthReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx  string `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	Err string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *SendTransactionEthReply) Reset() {
	*x = SendTransactionEthReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTransactionEthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionEthReply) ProtoMessage() {}

func (x *SendTransactionEthReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionEthReply.ProtoReflect.Descriptor instead.
func (*SendTransactionEthReply) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{15}
}

func (x *SendTransactionEthReply) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

func (x *SendTransactionEthReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type EthBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *EthBalanceRequest) Reset() {
	*x = EthBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthBalanceRequest) ProtoMessage() {}

func (x *EthBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthBalanceRequest.ProtoReflect.Descriptor instead.
func (*EthBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{16}
}

func (x *EthBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type EthBalanceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance string `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Err     string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *EthBalanceReply) Reset() {
	*x = EthBalanceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EthBalanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EthBalanceReply) ProtoMessage() {}

func (x *EthBalanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EthBalanceReply.ProtoReflect.Descriptor instead.
func (*EthBalanceReply) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{17}
}

func (x *EthBalanceReply) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *EthBalanceReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type TransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx string `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{18}
}

func (x *TransactionRequest) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

type TransactionReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status uint64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *TransactionReply) Reset() {
	*x = TransactionReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionReply) ProtoMessage() {}

func (x *TransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionReply.ProtoReflect.Descriptor instead.
func (*TransactionReply) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{19}
}

func (x *TransactionReply) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GenerateKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateKeyRequest) Reset() {
	*x = GenerateKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyRequest) ProtoMessage() {}

func (x *GenerateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{20}
}

type GenerateKeyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address    string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PrivateKey string `protobuf:"bytes,2,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	Err        string `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *GenerateKeyReply) Reset() {
	*x = GenerateKeyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyReply) ProtoMessage() {}

func (x *GenerateKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyReply.ProtoReflect.Descriptor instead.
func (*GenerateKeyReply) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{21}
}

func (x *GenerateKeyReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GenerateKeyReply) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *GenerateKeyReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type PushOneRequest_SendBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddressTwo string                          `protobuf:"bytes,2,opt,name=addressTwo,proto3" json:"addressTwo,omitempty"`
	Address    []*PushOneRequest_SendBody_List `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
}

func (x *PushOneRequest_SendBody) Reset() {
	*x = PushOneRequest_SendBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushOneRequest_SendBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOneRequest_SendBody) ProtoMessage() {}

func (x *PushOneRequest_SendBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOneRequest_SendBody.ProtoReflect.Descriptor instead.
func (*PushOneRequest_SendBody) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{4, 0}
}

func (x *PushOneRequest_SendBody) GetAddressTwo() string {
	if x != nil {
		return x.AddressTwo
	}
	return ""
}

func (x *PushOneRequest_SendBody) GetAddress() []*PushOneRequest_SendBody_List {
	if x != nil {
		return x.Address
	}
	return nil
}

type PushOneRequest_SendBody_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	One     string `protobuf:"bytes,2,opt,name=one,proto3" json:"one,omitempty"`
}

func (x *PushOneRequest_SendBody_List) Reset() {
	*x = PushOneRequest_SendBody_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushOneRequest_SendBody_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOneRequest_SendBody_List) ProtoMessage() {}

func (x *PushOneRequest_SendBody_List) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOneRequest_SendBody_List.ProtoReflect.Descriptor instead.
func (*PushOneRequest_SendBody_List) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *PushOneRequest_SendBody_List) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PushOneRequest_SendBody_List) GetOne() string {
	if x != nil {
		return x.One
	}
	return ""
}

type PushThreeFourRequest_SendBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []*PushThreeFourRequest_SendBody_List `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
}

func (x *PushThreeFourRequest_SendBody) Reset() {
	*x = PushThreeFourRequest_SendBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushThreeFourRequest_SendBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushThreeFourRequest_SendBody) ProtoMessage() {}

func (x *PushThreeFourRequest_SendBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushThreeFourRequest_SendBody.ProtoReflect.Descriptor instead.
func (*PushThreeFourRequest_SendBody) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{6, 0}
}

func (x *PushThreeFourRequest_SendBody) GetAddress() []*PushThreeFourRequest_SendBody_List {
	if x != nil {
		return x.Address
	}
	return nil
}

type PushThreeFourRequest_SendBody_List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Three   string `protobuf:"bytes,2,opt,name=three,proto3" json:"three,omitempty"`
	Four    string `protobuf:"bytes,3,opt,name=Four,proto3" json:"Four,omitempty"`
}

func (x *PushThreeFourRequest_SendBody_List) Reset() {
	*x = PushThreeFourRequest_SendBody_List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushThreeFourRequest_SendBody_List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushThreeFourRequest_SendBody_List) ProtoMessage() {}

func (x *PushThreeFourRequest_SendBody_List) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushThreeFourRequest_SendBody_List.ProtoReflect.Descriptor instead.
func (*PushThreeFourRequest_SendBody_List) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{6, 0, 0}
}

func (x *PushThreeFourRequest_SendBody_List) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PushThreeFourRequest_SendBody_List) GetThree() string {
	if x != nil {
		return x.Three
	}
	return ""
}

func (x *PushThreeFourRequest_SendBody_List) GetFour() string {
	if x != nil {
		return x.Four
	}
	return ""
}

type SendTransactionRequest_SendBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey string `protobuf:"bytes,1,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	ToAddr     string `protobuf:"bytes,2,opt,name=toAddr,proto3" json:"toAddr,omitempty"`
	Token      string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	Amount     string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *SendTransactionRequest_SendBody) Reset() {
	*x = SendTransactionRequest_SendBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTransactionRequest_SendBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionRequest_SendBody) ProtoMessage() {}

func (x *SendTransactionRequest_SendBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionRequest_SendBody.ProtoReflect.Descriptor instead.
func (*SendTransactionRequest_SendBody) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{12, 0}
}

func (x *SendTransactionRequest_SendBody) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *SendTransactionRequest_SendBody) GetToAddr() string {
	if x != nil {
		return x.ToAddr
	}
	return ""
}

func (x *SendTransactionRequest_SendBody) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SendTransactionRequest_SendBody) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type SendTransactionEthRequest_SendBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivateKey string `protobuf:"bytes,1,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	ToAddr     string `protobuf:"bytes,2,opt,name=toAddr,proto3" json:"toAddr,omitempty"`
	Amount     string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *SendTransactionEthRequest_SendBody) Reset() {
	*x = SendTransactionEthRequest_SendBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_requestEth_v1_transaction_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendTransactionEthRequest_SendBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionEthRequest_SendBody) ProtoMessage() {}

func (x *SendTransactionEthRequest_SendBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_requestEth_v1_transaction_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionEthRequest_SendBody.ProtoReflect.Descriptor instead.
func (*SendTransactionEthRequest_SendBody) Descriptor() ([]byte, []int) {
	return file_api_requestEth_v1_transaction_proto_rawDescGZIP(), []int{14, 0}
}

func (x *SendTransactionEthRequest_SendBody) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *SendTransactionEthRequest_SendBody) GetToAddr() string {
	if x != nil {
		return x.ToAddr
	}
	return ""
}

func (x *SendTransactionEthRequest_SendBody) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

var File_api_requestEth_v1_transaction_proto protoreflect.FileDescriptor

var file_api_requestEth_v1_transaction_proto_rawDesc = []byte{
	0x0a, 0x23, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68,
	0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x69, 0x72,
	0x22, 0x56, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x73,
	0x4f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x73, 0x4f, 0x6e, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x73, 0x54, 0x77, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x73, 0x54, 0x77, 0x6f, 0x22, 0x29, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x9b, 0x02, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6f, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x77, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x74, 0x77, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x72, 0x65, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x68, 0x72, 0x65, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x6f, 0x75, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x6f, 0x75,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x70, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x70, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a,
	0x0d, 0x6c, 0x70, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x70, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x6e, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x6e, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x77, 0x6f, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x77, 0x6f, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12,
	0x20, 0x0a, 0x0b, 0x74, 0x68, 0x72, 0x65, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x68, 0x72, 0x65, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x6f, 0x75, 0x72, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x6f, 0x75, 0x72, 0x4c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x22, 0x85, 0x02, 0x0a, 0x0e, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x47, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x73, 0x68,
	0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x6f, 0x64, 0x79, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0xa9, 0x01,
	0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x77, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x77, 0x6f, 0x12, 0x49, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x75, 0x73, 0x68, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x32, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x6e, 0x65, 0x22, 0x20, 0x0a, 0x0c, 0x50, 0x75, 0x73,
	0x68, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x8f, 0x02, 0x0a, 0x14,
	0x50, 0x75, 0x73, 0x68, 0x54, 0x68, 0x72, 0x65, 0x65, 0x46, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x4d, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x73, 0x68,
	0x54, 0x68, 0x72, 0x65, 0x65, 0x46, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x42,
	0x6f, 0x64, 0x79, 0x1a, 0xa7, 0x01, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79,
	0x12, 0x4f, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x35, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45,
	0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x68, 0x72, 0x65, 0x65, 0x46,
	0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x6f, 0x64, 0x79, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x1a, 0x4a, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x68, 0x72, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x68, 0x72, 0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x6f, 0x75,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x6f, 0x75, 0x72, 0x22, 0x26, 0x0a,
	0x12, 0x50, 0x75, 0x73, 0x68, 0x54, 0x68, 0x72, 0x65, 0x65, 0x46, 0x6f, 0x75, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x40, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53,
	0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x3c, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x53, 0x69, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x45, 0x0a, 0x13, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x3f, 0x0a, 0x11,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65,
	0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0xdb, 0x01,
	0x0a, 0x16, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4f, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64,
	0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x70, 0x0a, 0x08, 0x53, 0x65, 0x6e,
	0x64, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x14, 0x53,
	0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x74, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0xcb, 0x01, 0x0a, 0x19, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x52, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x08, 0x73,
	0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x5a, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x6f, 0x64, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x3b, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x78, 0x12, 0x10,
	0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72,
	0x22, 0x2d, 0x0a, 0x11, 0x45, 0x74, 0x68, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x3d, 0x0a, 0x0f, 0x45, 0x74, 0x68, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x24,
	0x0a, 0x12, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x74, 0x78, 0x22, 0x2a, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5e, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x32, 0xd1, 0x0a, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x8a, 0x01, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x23,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x3a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64,
	0x79, 0x22, 0x10, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x97, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x74, 0x68, 0x12, 0x2c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x74, 0x68, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x3a, 0x09, 0x73, 0x65,
	0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x14, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x74, 0x68, 0x12, 0x78, 0x0a,
	0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17,
	0x12, 0x15, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2f, 0x7b, 0x74, 0x78, 0x7d, 0x12, 0x70, 0x0a, 0x0a, 0x45, 0x74, 0x68, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x74, 0x68, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x74, 0x68, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x74,
	0x68, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x74, 0x0a, 0x0b, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x12,
	0x77, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x64, 0x74,
	0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x6c, 0x0a, 0x09, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x53, 0x69, 0x67, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x53, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x69, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12, 0x0f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x5f, 0x73, 0x69, 0x67, 0x12, 0x74, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x73, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x73, 0x12, 0x60, 0x0a, 0x06,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e,
	0x12, 0x0c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x12, 0x6f,
	0x0a, 0x07, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x6e, 0x65, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75,
	0x73, 0x68, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x20, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x3a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79,
	0x22, 0x0d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x6f, 0x6e, 0x65, 0x12,
	0x88, 0x01, 0x0a, 0x0d, 0x50, 0x75, 0x73, 0x68, 0x54, 0x68, 0x72, 0x65, 0x65, 0x46, 0x6f, 0x75,
	0x72, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45,
	0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x68, 0x72, 0x65, 0x65, 0x46,
	0x6f, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x75, 0x73, 0x68, 0x54, 0x68, 0x72, 0x65, 0x65, 0x46, 0x6f, 0x75, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21, 0x3a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f,
	0x62, 0x6f, 0x64, 0x79, 0x22, 0x14, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x5f,
	0x74, 0x68, 0x72, 0x65, 0x65, 0x5f, 0x66, 0x6f, 0x75, 0x72, 0x42, 0x54, 0x0a, 0x1c, 0x64, 0x65,
	0x76, 0x2e, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x42, 0x11, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x56, 0x31, 0x50, 0x01, 0x5a,
	0x1f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_requestEth_v1_transaction_proto_rawDescOnce sync.Once
	file_api_requestEth_v1_transaction_proto_rawDescData = file_api_requestEth_v1_transaction_proto_rawDesc
)

func file_api_requestEth_v1_transaction_proto_rawDescGZIP() []byte {
	file_api_requestEth_v1_transaction_proto_rawDescOnce.Do(func() {
		file_api_requestEth_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_requestEth_v1_transaction_proto_rawDescData)
	})
	return file_api_requestEth_v1_transaction_proto_rawDescData
}

var file_api_requestEth_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_requestEth_v1_transaction_proto_goTypes = []interface{}{
	(*GetReservesRequest)(nil),                 // 0: api.requestEth.v1.GetReservesRequest
	(*GetReservesReply)(nil),                   // 1: api.requestEth.v1.GetReservesReply
	(*GetAllRequest)(nil),                      // 2: api.requestEth.v1.GetAllRequest
	(*GetAllReply)(nil),                        // 3: api.requestEth.v1.GetAllReply
	(*PushOneRequest)(nil),                     // 4: api.requestEth.v1.PushOneRequest
	(*PushOneReply)(nil),                       // 5: api.requestEth.v1.PushOneReply
	(*PushThreeFourRequest)(nil),               // 6: api.requestEth.v1.PushThreeFourRequest
	(*PushThreeFourReply)(nil),                 // 7: api.requestEth.v1.PushThreeFourReply
	(*VerifySigRequest)(nil),                   // 8: api.requestEth.v1.VerifySigRequest
	(*VerifySigReply)(nil),                     // 9: api.requestEth.v1.VerifySigReply
	(*TokenBalanceRequest)(nil),                // 10: api.requestEth.v1.TokenBalanceRequest
	(*TokenBalanceReply)(nil),                  // 11: api.requestEth.v1.TokenBalanceReply
	(*SendTransactionRequest)(nil),             // 12: api.requestEth.v1.SendTransactionRequest
	(*SendTransactionReply)(nil),               // 13: api.requestEth.v1.SendTransactionReply
	(*SendTransactionEthRequest)(nil),          // 14: api.requestEth.v1.SendTransactionEthRequest
	(*SendTransactionEthReply)(nil),            // 15: api.requestEth.v1.SendTransactionEthReply
	(*EthBalanceRequest)(nil),                  // 16: api.requestEth.v1.EthBalanceRequest
	(*EthBalanceReply)(nil),                    // 17: api.requestEth.v1.EthBalanceReply
	(*TransactionRequest)(nil),                 // 18: api.requestEth.v1.TransactionRequest
	(*TransactionReply)(nil),                   // 19: api.requestEth.v1.TransactionReply
	(*GenerateKeyRequest)(nil),                 // 20: api.requestEth.v1.GenerateKeyRequest
	(*GenerateKeyReply)(nil),                   // 21: api.requestEth.v1.GenerateKeyReply
	(*PushOneRequest_SendBody)(nil),            // 22: api.requestEth.v1.PushOneRequest.SendBody
	(*PushOneRequest_SendBody_List)(nil),       // 23: api.requestEth.v1.PushOneRequest.SendBody.List
	(*PushThreeFourRequest_SendBody)(nil),      // 24: api.requestEth.v1.PushThreeFourRequest.SendBody
	(*PushThreeFourRequest_SendBody_List)(nil), // 25: api.requestEth.v1.PushThreeFourRequest.SendBody.List
	(*SendTransactionRequest_SendBody)(nil),    // 26: api.requestEth.v1.SendTransactionRequest.SendBody
	(*SendTransactionEthRequest_SendBody)(nil), // 27: api.requestEth.v1.SendTransactionEthRequest.SendBody
}
var file_api_requestEth_v1_transaction_proto_depIdxs = []int32{
	22, // 0: api.requestEth.v1.PushOneRequest.send_body:type_name -> api.requestEth.v1.PushOneRequest.SendBody
	24, // 1: api.requestEth.v1.PushThreeFourRequest.send_body:type_name -> api.requestEth.v1.PushThreeFourRequest.SendBody
	26, // 2: api.requestEth.v1.SendTransactionRequest.send_body:type_name -> api.requestEth.v1.SendTransactionRequest.SendBody
	27, // 3: api.requestEth.v1.SendTransactionEthRequest.send_body:type_name -> api.requestEth.v1.SendTransactionEthRequest.SendBody
	23, // 4: api.requestEth.v1.PushOneRequest.SendBody.address:type_name -> api.requestEth.v1.PushOneRequest.SendBody.List
	25, // 5: api.requestEth.v1.PushThreeFourRequest.SendBody.address:type_name -> api.requestEth.v1.PushThreeFourRequest.SendBody.List
	12, // 6: api.requestEth.v1.Transaction.SendTransaction:input_type -> api.requestEth.v1.SendTransactionRequest
	14, // 7: api.requestEth.v1.Transaction.SendTransactionEth:input_type -> api.requestEth.v1.SendTransactionEthRequest
	18, // 8: api.requestEth.v1.Transaction.Transaction:input_type -> api.requestEth.v1.TransactionRequest
	16, // 9: api.requestEth.v1.Transaction.EthBalance:input_type -> api.requestEth.v1.EthBalanceRequest
	20, // 10: api.requestEth.v1.Transaction.GenerateKey:input_type -> api.requestEth.v1.GenerateKeyRequest
	10, // 11: api.requestEth.v1.Transaction.TokenBalance:input_type -> api.requestEth.v1.TokenBalanceRequest
	8,  // 12: api.requestEth.v1.Transaction.VerifySig:input_type -> api.requestEth.v1.VerifySigRequest
	0,  // 13: api.requestEth.v1.Transaction.GetReserves:input_type -> api.requestEth.v1.GetReservesRequest
	2,  // 14: api.requestEth.v1.Transaction.GetAll:input_type -> api.requestEth.v1.GetAllRequest
	4,  // 15: api.requestEth.v1.Transaction.PushOne:input_type -> api.requestEth.v1.PushOneRequest
	6,  // 16: api.requestEth.v1.Transaction.PushThreeFour:input_type -> api.requestEth.v1.PushThreeFourRequest
	13, // 17: api.requestEth.v1.Transaction.SendTransaction:output_type -> api.requestEth.v1.SendTransactionReply
	15, // 18: api.requestEth.v1.Transaction.SendTransactionEth:output_type -> api.requestEth.v1.SendTransactionEthReply
	19, // 19: api.requestEth.v1.Transaction.Transaction:output_type -> api.requestEth.v1.TransactionReply
	17, // 20: api.requestEth.v1.Transaction.EthBalance:output_type -> api.requestEth.v1.EthBalanceReply
	21, // 21: api.requestEth.v1.Transaction.GenerateKey:output_type -> api.requestEth.v1.GenerateKeyReply
	11, // 22: api.requestEth.v1.Transaction.TokenBalance:output_type -> api.requestEth.v1.TokenBalanceReply
	9,  // 23: api.requestEth.v1.Transaction.VerifySig:output_type -> api.requestEth.v1.VerifySigReply
	1,  // 24: api.requestEth.v1.Transaction.GetReserves:output_type -> api.requestEth.v1.GetReservesReply
	3,  // 25: api.requestEth.v1.Transaction.GetAll:output_type -> api.requestEth.v1.GetAllReply
	5,  // 26: api.requestEth.v1.Transaction.PushOne:output_type -> api.requestEth.v1.PushOneReply
	7,  // 27: api.requestEth.v1.Transaction.PushThreeFour:output_type -> api.requestEth.v1.PushThreeFourReply
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_requestEth_v1_transaction_proto_init() }
func file_api_requestEth_v1_transaction_proto_init() {
	if File_api_requestEth_v1_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_requestEth_v1_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReservesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReservesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushOneReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushThreeFourRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushThreeFourReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifySigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifySigReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenBalanceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTransactionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTransactionEthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTransactionEthReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EthBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EthBalanceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateKeyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushOneRequest_SendBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushOneRequest_SendBody_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushThreeFourRequest_SendBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushThreeFourRequest_SendBody_List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTransactionRequest_SendBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_requestEth_v1_transaction_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendTransactionEthRequest_SendBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_requestEth_v1_transaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_requestEth_v1_transaction_proto_goTypes,
		DependencyIndexes: file_api_requestEth_v1_transaction_proto_depIdxs,
		MessageInfos:      file_api_requestEth_v1_transaction_proto_msgTypes,
	}.Build()
	File_api_requestEth_v1_transaction_proto = out.File
	file_api_requestEth_v1_transaction_proto_rawDesc = nil
	file_api_requestEth_v1_transaction_proto_goTypes = nil
	file_api_requestEth_v1_transaction_proto_depIdxs = nil
}
