// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v3.21.7
// source: api/requestEth/v1/transaction.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTransactionAddLiquidity = "/api.requestEth.v1.Transaction/AddLiquidity"
const OperationTransactionAddWhite = "/api.requestEth.v1.Transaction/AddWhite"
const OperationTransactionBuyAICAT = "/api.requestEth.v1.Transaction/BuyAICAT"
const OperationTransactionEthBalance = "/api.requestEth.v1.Transaction/EthBalance"
const OperationTransactionGenerateKey = "/api.requestEth.v1.Transaction/GenerateKey"
const OperationTransactionGetAll = "/api.requestEth.v1.Transaction/GetAll"
const OperationTransactionGetArray = "/api.requestEth.v1.Transaction/GetArray"
const OperationTransactionGetBuyByOrderId = "/api.requestEth.v1.Transaction/GetBuyByOrderId"
const OperationTransactionGetDailyFee = "/api.requestEth.v1.Transaction/GetDailyFee"
const OperationTransactionGetLpByOrderId = "/api.requestEth.v1.Transaction/GetLpByOrderId"
const OperationTransactionGetReserves = "/api.requestEth.v1.Transaction/GetReserves"
const OperationTransactionGetUserLp = "/api.requestEth.v1.Transaction/GetUserLp"
const OperationTransactionRemoveLiquidity = "/api.requestEth.v1.Transaction/RemoveLiquidity"
const OperationTransactionSendTransaction = "/api.requestEth.v1.Transaction/SendTransaction"
const OperationTransactionSendTransactionEth = "/api.requestEth.v1.Transaction/SendTransactionEth"
const OperationTransactionTokenBalance = "/api.requestEth.v1.Transaction/TokenBalance"
const OperationTransactionTransaction = "/api.requestEth.v1.Transaction/Transaction"
const OperationTransactionVerifySig = "/api.requestEth.v1.Transaction/VerifySig"
const OperationTransactionWithdrawAICAT = "/api.requestEth.v1.Transaction/WithdrawAICAT"

type TransactionHTTPServer interface {
	AddLiquidity(context.Context, *AddLiquidityRequest) (*AddLiquidityReply, error)
	AddWhite(context.Context, *AddWhiteRequest) (*AddWhiteReply, error)
	BuyAICAT(context.Context, *BuyAICATRequest) (*BuyAICATReply, error)
	EthBalance(context.Context, *EthBalanceRequest) (*EthBalanceReply, error)
	GenerateKey(context.Context, *GenerateKeyRequest) (*GenerateKeyReply, error)
	GetAll(context.Context, *GetAllRequest) (*GetAllReply, error)
	GetArray(context.Context, *GetArrayRequest) (*GetArrayReply, error)
	GetBuyByOrderId(context.Context, *GetBuyByOrderIdRequest) (*GetBuyByOrderIdReply, error)
	GetDailyFee(context.Context, *GetDailyFeeRequest) (*GetDailyFeeReply, error)
	GetLpByOrderId(context.Context, *GetLpByOrderIdRequest) (*GetLpByOrderIdReply, error)
	GetReserves(context.Context, *GetReservesRequest) (*GetReservesReply, error)
	GetUserLp(context.Context, *GetUserLpRequest) (*GetUserLpReply, error)
	RemoveLiquidity(context.Context, *RemoveLiquidityRequest) (*RemoveLiquidityReply, error)
	SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionReply, error)
	SendTransactionEth(context.Context, *SendTransactionEthRequest) (*SendTransactionEthReply, error)
	TokenBalance(context.Context, *TokenBalanceRequest) (*TokenBalanceReply, error)
	Transaction(context.Context, *TransactionRequest) (*TransactionReply, error)
	VerifySig(context.Context, *VerifySigRequest) (*VerifySigReply, error)
	WithdrawAICAT(context.Context, *WithdrawAICATRequest) (*WithdrawAICATReply, error)
}

func RegisterTransactionHTTPServer(s *http.Server, srv TransactionHTTPServer) {
	r := s.Route("/")
	r.POST("/api/transaction", _Transaction_SendTransaction0_HTTP_Handler(srv))
	r.POST("/api/transaction_eth", _Transaction_SendTransactionEth0_HTTP_Handler(srv))
	r.GET("/api/transaction/{tx}", _Transaction_Transaction0_HTTP_Handler(srv))
	r.GET("/api/eth_balance", _Transaction_EthBalance0_HTTP_Handler(srv))
	r.GET("/api/generate_key", _Transaction_GenerateKey0_HTTP_Handler(srv))
	r.GET("/api/usdt_balance", _Transaction_TokenBalance0_HTTP_Handler(srv))
	r.GET("/api/verify_sig", _Transaction_VerifySig0_HTTP_Handler(srv))
	r.GET("/api/get_reserves", _Transaction_GetReserves0_HTTP_Handler(srv))
	r.GET("/api/get_all", _Transaction_GetAll0_HTTP_Handler(srv))
	r.GET("/api/get_array", _Transaction_GetArray0_HTTP_Handler(srv))
	r.GET("/api/get_lp", _Transaction_GetLpByOrderId0_HTTP_Handler(srv))
	r.GET("/api/get_buy", _Transaction_GetBuyByOrderId0_HTTP_Handler(srv))
	r.GET("/api/get_user_lp", _Transaction_GetUserLp0_HTTP_Handler(srv))
	r.GET("/api/get_daily_fee", _Transaction_GetDailyFee0_HTTP_Handler(srv))
	r.POST("/api/add_liquidity", _Transaction_AddLiquidity0_HTTP_Handler(srv))
	r.POST("/api/remove_liquidity", _Transaction_RemoveLiquidity0_HTTP_Handler(srv))
	r.POST("/api/buy", _Transaction_BuyAICAT0_HTTP_Handler(srv))
	r.POST("/api/withdraw", _Transaction_WithdrawAICAT0_HTTP_Handler(srv))
	r.GET("/api/add_white", _Transaction_AddWhite0_HTTP_Handler(srv))
}

func _Transaction_SendTransaction0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendTransactionRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionSendTransaction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendTransaction(ctx, req.(*SendTransactionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendTransactionReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_SendTransactionEth0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendTransactionEthRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionSendTransactionEth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendTransactionEth(ctx, req.(*SendTransactionEthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendTransactionEthReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_Transaction0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TransactionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionTransaction)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Transaction(ctx, req.(*TransactionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TransactionReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_EthBalance0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EthBalanceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionEthBalance)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EthBalance(ctx, req.(*EthBalanceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EthBalanceReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_GenerateKey0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateKeyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionGenerateKey)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateKey(ctx, req.(*GenerateKeyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateKeyReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_TokenBalance0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TokenBalanceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionTokenBalance)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TokenBalance(ctx, req.(*TokenBalanceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TokenBalanceReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_VerifySig0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in VerifySigRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionVerifySig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.VerifySig(ctx, req.(*VerifySigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*VerifySigReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_GetReserves0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetReservesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionGetReserves)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetReserves(ctx, req.(*GetReservesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetReservesReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_GetAll0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAllRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionGetAll)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAll(ctx, req.(*GetAllRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAllReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_GetArray0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetArrayRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionGetArray)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetArray(ctx, req.(*GetArrayRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetArrayReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_GetLpByOrderId0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLpByOrderIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionGetLpByOrderId)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLpByOrderId(ctx, req.(*GetLpByOrderIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLpByOrderIdReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_GetBuyByOrderId0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetBuyByOrderIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionGetBuyByOrderId)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBuyByOrderId(ctx, req.(*GetBuyByOrderIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetBuyByOrderIdReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_GetUserLp0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserLpRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionGetUserLp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserLp(ctx, req.(*GetUserLpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserLpReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_GetDailyFee0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDailyFeeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionGetDailyFee)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDailyFee(ctx, req.(*GetDailyFeeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDailyFeeReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_AddLiquidity0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddLiquidityRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionAddLiquidity)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddLiquidity(ctx, req.(*AddLiquidityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddLiquidityReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_RemoveLiquidity0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveLiquidityRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionRemoveLiquidity)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveLiquidity(ctx, req.(*RemoveLiquidityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveLiquidityReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_BuyAICAT0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BuyAICATRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionBuyAICAT)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BuyAICAT(ctx, req.(*BuyAICATRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BuyAICATReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_WithdrawAICAT0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WithdrawAICATRequest
		if err := ctx.Bind(&in.SendBody); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionWithdrawAICAT)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.WithdrawAICAT(ctx, req.(*WithdrawAICATRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WithdrawAICATReply)
		return ctx.Result(200, reply)
	}
}

func _Transaction_AddWhite0_HTTP_Handler(srv TransactionHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddWhiteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTransactionAddWhite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddWhite(ctx, req.(*AddWhiteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddWhiteReply)
		return ctx.Result(200, reply)
	}
}

type TransactionHTTPClient interface {
	AddLiquidity(ctx context.Context, req *AddLiquidityRequest, opts ...http.CallOption) (rsp *AddLiquidityReply, err error)
	AddWhite(ctx context.Context, req *AddWhiteRequest, opts ...http.CallOption) (rsp *AddWhiteReply, err error)
	BuyAICAT(ctx context.Context, req *BuyAICATRequest, opts ...http.CallOption) (rsp *BuyAICATReply, err error)
	EthBalance(ctx context.Context, req *EthBalanceRequest, opts ...http.CallOption) (rsp *EthBalanceReply, err error)
	GenerateKey(ctx context.Context, req *GenerateKeyRequest, opts ...http.CallOption) (rsp *GenerateKeyReply, err error)
	GetAll(ctx context.Context, req *GetAllRequest, opts ...http.CallOption) (rsp *GetAllReply, err error)
	GetArray(ctx context.Context, req *GetArrayRequest, opts ...http.CallOption) (rsp *GetArrayReply, err error)
	GetBuyByOrderId(ctx context.Context, req *GetBuyByOrderIdRequest, opts ...http.CallOption) (rsp *GetBuyByOrderIdReply, err error)
	GetDailyFee(ctx context.Context, req *GetDailyFeeRequest, opts ...http.CallOption) (rsp *GetDailyFeeReply, err error)
	GetLpByOrderId(ctx context.Context, req *GetLpByOrderIdRequest, opts ...http.CallOption) (rsp *GetLpByOrderIdReply, err error)
	GetReserves(ctx context.Context, req *GetReservesRequest, opts ...http.CallOption) (rsp *GetReservesReply, err error)
	GetUserLp(ctx context.Context, req *GetUserLpRequest, opts ...http.CallOption) (rsp *GetUserLpReply, err error)
	RemoveLiquidity(ctx context.Context, req *RemoveLiquidityRequest, opts ...http.CallOption) (rsp *RemoveLiquidityReply, err error)
	SendTransaction(ctx context.Context, req *SendTransactionRequest, opts ...http.CallOption) (rsp *SendTransactionReply, err error)
	SendTransactionEth(ctx context.Context, req *SendTransactionEthRequest, opts ...http.CallOption) (rsp *SendTransactionEthReply, err error)
	TokenBalance(ctx context.Context, req *TokenBalanceRequest, opts ...http.CallOption) (rsp *TokenBalanceReply, err error)
	Transaction(ctx context.Context, req *TransactionRequest, opts ...http.CallOption) (rsp *TransactionReply, err error)
	VerifySig(ctx context.Context, req *VerifySigRequest, opts ...http.CallOption) (rsp *VerifySigReply, err error)
	WithdrawAICAT(ctx context.Context, req *WithdrawAICATRequest, opts ...http.CallOption) (rsp *WithdrawAICATReply, err error)
}

type TransactionHTTPClientImpl struct {
	cc *http.Client
}

func NewTransactionHTTPClient(client *http.Client) TransactionHTTPClient {
	return &TransactionHTTPClientImpl{client}
}

func (c *TransactionHTTPClientImpl) AddLiquidity(ctx context.Context, in *AddLiquidityRequest, opts ...http.CallOption) (*AddLiquidityReply, error) {
	var out AddLiquidityReply
	pattern := "/api/add_liquidity"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTransactionAddLiquidity))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) AddWhite(ctx context.Context, in *AddWhiteRequest, opts ...http.CallOption) (*AddWhiteReply, error) {
	var out AddWhiteReply
	pattern := "/api/add_white"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionAddWhite))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) BuyAICAT(ctx context.Context, in *BuyAICATRequest, opts ...http.CallOption) (*BuyAICATReply, error) {
	var out BuyAICATReply
	pattern := "/api/buy"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTransactionBuyAICAT))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) EthBalance(ctx context.Context, in *EthBalanceRequest, opts ...http.CallOption) (*EthBalanceReply, error) {
	var out EthBalanceReply
	pattern := "/api/eth_balance"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionEthBalance))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...http.CallOption) (*GenerateKeyReply, error) {
	var out GenerateKeyReply
	pattern := "/api/generate_key"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionGenerateKey))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) GetAll(ctx context.Context, in *GetAllRequest, opts ...http.CallOption) (*GetAllReply, error) {
	var out GetAllReply
	pattern := "/api/get_all"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionGetAll))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) GetArray(ctx context.Context, in *GetArrayRequest, opts ...http.CallOption) (*GetArrayReply, error) {
	var out GetArrayReply
	pattern := "/api/get_array"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionGetArray))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) GetBuyByOrderId(ctx context.Context, in *GetBuyByOrderIdRequest, opts ...http.CallOption) (*GetBuyByOrderIdReply, error) {
	var out GetBuyByOrderIdReply
	pattern := "/api/get_buy"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionGetBuyByOrderId))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) GetDailyFee(ctx context.Context, in *GetDailyFeeRequest, opts ...http.CallOption) (*GetDailyFeeReply, error) {
	var out GetDailyFeeReply
	pattern := "/api/get_daily_fee"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionGetDailyFee))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) GetLpByOrderId(ctx context.Context, in *GetLpByOrderIdRequest, opts ...http.CallOption) (*GetLpByOrderIdReply, error) {
	var out GetLpByOrderIdReply
	pattern := "/api/get_lp"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionGetLpByOrderId))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) GetReserves(ctx context.Context, in *GetReservesRequest, opts ...http.CallOption) (*GetReservesReply, error) {
	var out GetReservesReply
	pattern := "/api/get_reserves"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionGetReserves))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) GetUserLp(ctx context.Context, in *GetUserLpRequest, opts ...http.CallOption) (*GetUserLpReply, error) {
	var out GetUserLpReply
	pattern := "/api/get_user_lp"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionGetUserLp))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) RemoveLiquidity(ctx context.Context, in *RemoveLiquidityRequest, opts ...http.CallOption) (*RemoveLiquidityReply, error) {
	var out RemoveLiquidityReply
	pattern := "/api/remove_liquidity"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTransactionRemoveLiquidity))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...http.CallOption) (*SendTransactionReply, error) {
	var out SendTransactionReply
	pattern := "/api/transaction"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTransactionSendTransaction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) SendTransactionEth(ctx context.Context, in *SendTransactionEthRequest, opts ...http.CallOption) (*SendTransactionEthReply, error) {
	var out SendTransactionEthReply
	pattern := "/api/transaction_eth"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTransactionSendTransactionEth))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) TokenBalance(ctx context.Context, in *TokenBalanceRequest, opts ...http.CallOption) (*TokenBalanceReply, error) {
	var out TokenBalanceReply
	pattern := "/api/usdt_balance"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionTokenBalance))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) Transaction(ctx context.Context, in *TransactionRequest, opts ...http.CallOption) (*TransactionReply, error) {
	var out TransactionReply
	pattern := "/api/transaction/{tx}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionTransaction))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) VerifySig(ctx context.Context, in *VerifySigRequest, opts ...http.CallOption) (*VerifySigReply, error) {
	var out VerifySigReply
	pattern := "/api/verify_sig"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTransactionVerifySig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TransactionHTTPClientImpl) WithdrawAICAT(ctx context.Context, in *WithdrawAICATRequest, opts ...http.CallOption) (*WithdrawAICATReply, error) {
	var out WithdrawAICATReply
	pattern := "/api/withdraw"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTransactionWithdrawAICAT))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.SendBody, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
