// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.7
// source: api/requestEth/v1/transaction.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Transaction_SendTransaction_FullMethodName      = "/api.requestEth.v1.Transaction/SendTransaction"
	Transaction_SendTransactionEth_FullMethodName   = "/api.requestEth.v1.Transaction/SendTransactionEth"
	Transaction_Transaction_FullMethodName          = "/api.requestEth.v1.Transaction/Transaction"
	Transaction_EthBalance_FullMethodName           = "/api.requestEth.v1.Transaction/EthBalance"
	Transaction_GenerateKey_FullMethodName          = "/api.requestEth.v1.Transaction/GenerateKey"
	Transaction_TokenBalance_FullMethodName         = "/api.requestEth.v1.Transaction/TokenBalance"
	Transaction_VerifySig_FullMethodName            = "/api.requestEth.v1.Transaction/VerifySig"
	Transaction_GetReserves_FullMethodName          = "/api.requestEth.v1.Transaction/GetReserves"
	Transaction_GetAll_FullMethodName               = "/api.requestEth.v1.Transaction/GetAll"
	Transaction_GetAllTwo_FullMethodName            = "/api.requestEth.v1.Transaction/GetAllTwo"
	Transaction_GetArray_FullMethodName             = "/api.requestEth.v1.Transaction/GetArray"
	Transaction_GetLpByOrderId_FullMethodName       = "/api.requestEth.v1.Transaction/GetLpByOrderId"
	Transaction_GetBuyByOrderId_FullMethodName      = "/api.requestEth.v1.Transaction/GetBuyByOrderId"
	Transaction_GetUserLp_FullMethodName            = "/api.requestEth.v1.Transaction/GetUserLp"
	Transaction_GetDailyFee_FullMethodName          = "/api.requestEth.v1.Transaction/GetDailyFee"
	Transaction_AddLiquidity_FullMethodName         = "/api.requestEth.v1.Transaction/AddLiquidity"
	Transaction_RemoveLiquidity_FullMethodName      = "/api.requestEth.v1.Transaction/RemoveLiquidity"
	Transaction_BuyAICAT_FullMethodName             = "/api.requestEth.v1.Transaction/BuyAICAT"
	Transaction_WithdrawAICAT_FullMethodName        = "/api.requestEth.v1.Transaction/WithdrawAICAT"
	Transaction_SendAICAT_FullMethodName            = "/api.requestEth.v1.Transaction/SendAICAT"
	Transaction_GetBuyAICATByOrderId_FullMethodName = "/api.requestEth.v1.Transaction/GetBuyAICATByOrderId"
	Transaction_AddWhite_FullMethodName             = "/api.requestEth.v1.Transaction/AddWhite"
	Transaction_GetBoxAllLength_FullMethodName      = "/api.requestEth.v1.Transaction/GetBoxAllLength"
	Transaction_GetBoxNew_FullMethodName            = "/api.requestEth.v1.Transaction/GetBoxNew"
	Transaction_GetBoxOpen_FullMethodName           = "/api.requestEth.v1.Transaction/GetBoxOpen"
	Transaction_SetReward_FullMethodName            = "/api.requestEth.v1.Transaction/SetReward"
	Transaction_SetRewardTwo_FullMethodName         = "/api.requestEth.v1.Transaction/SetRewardTwo"
	Transaction_GetBoxRewardEvent_FullMethodName    = "/api.requestEth.v1.Transaction/GetBoxRewardEvent"
)

// TransactionClient is the client API for Transaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionClient interface {
	SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionReply, error)
	SendTransactionEth(ctx context.Context, in *SendTransactionEthRequest, opts ...grpc.CallOption) (*SendTransactionEthReply, error)
	Transaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error)
	EthBalance(ctx context.Context, in *EthBalanceRequest, opts ...grpc.CallOption) (*EthBalanceReply, error)
	GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyReply, error)
	TokenBalance(ctx context.Context, in *TokenBalanceRequest, opts ...grpc.CallOption) (*TokenBalanceReply, error)
	VerifySig(ctx context.Context, in *VerifySigRequest, opts ...grpc.CallOption) (*VerifySigReply, error)
	GetReserves(ctx context.Context, in *GetReservesRequest, opts ...grpc.CallOption) (*GetReservesReply, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllReply, error)
	GetAllTwo(ctx context.Context, in *GetAllTwoRequest, opts ...grpc.CallOption) (*GetAllTwoReply, error)
	GetArray(ctx context.Context, in *GetArrayRequest, opts ...grpc.CallOption) (*GetArrayReply, error)
	GetLpByOrderId(ctx context.Context, in *GetLpByOrderIdRequest, opts ...grpc.CallOption) (*GetLpByOrderIdReply, error)
	GetBuyByOrderId(ctx context.Context, in *GetBuyByOrderIdRequest, opts ...grpc.CallOption) (*GetBuyByOrderIdReply, error)
	GetUserLp(ctx context.Context, in *GetUserLpRequest, opts ...grpc.CallOption) (*GetUserLpReply, error)
	GetDailyFee(ctx context.Context, in *GetDailyFeeRequest, opts ...grpc.CallOption) (*GetDailyFeeReply, error)
	AddLiquidity(ctx context.Context, in *AddLiquidityRequest, opts ...grpc.CallOption) (*AddLiquidityReply, error)
	RemoveLiquidity(ctx context.Context, in *RemoveLiquidityRequest, opts ...grpc.CallOption) (*RemoveLiquidityReply, error)
	BuyAICAT(ctx context.Context, in *BuyAICATRequest, opts ...grpc.CallOption) (*BuyAICATReply, error)
	WithdrawAICAT(ctx context.Context, in *WithdrawAICATRequest, opts ...grpc.CallOption) (*WithdrawAICATReply, error)
	SendAICAT(ctx context.Context, in *SendAICATRequest, opts ...grpc.CallOption) (*SendAICATReply, error)
	GetBuyAICATByOrderId(ctx context.Context, in *GetBuyAICATByOrderIdRequest, opts ...grpc.CallOption) (*GetBuyAICATByOrderIdReply, error)
	AddWhite(ctx context.Context, in *AddWhiteRequest, opts ...grpc.CallOption) (*AddWhiteReply, error)
	GetBoxAllLength(ctx context.Context, in *GetBoxAllRequest, opts ...grpc.CallOption) (*GetBoxAllReply, error)
	GetBoxNew(ctx context.Context, in *GetBoxNewRequest, opts ...grpc.CallOption) (*GetBoxNewReply, error)
	GetBoxOpen(ctx context.Context, in *GetBoxOpenRequest, opts ...grpc.CallOption) (*GetBoxOpenReply, error)
	SetReward(ctx context.Context, in *SetRewardRequest, opts ...grpc.CallOption) (*SetRewardReply, error)
	SetRewardTwo(ctx context.Context, in *SetRewardRequest, opts ...grpc.CallOption) (*SetRewardReply, error)
	GetBoxRewardEvent(ctx context.Context, in *GetBoxRewardEventRequest, opts ...grpc.CallOption) (*GetBoxRewardEventReply, error)
}

type transactionClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionClient(cc grpc.ClientConnInterface) TransactionClient {
	return &transactionClient{cc}
}

func (c *transactionClient) SendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionReply, error) {
	out := new(SendTransactionReply)
	err := c.cc.Invoke(ctx, Transaction_SendTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) SendTransactionEth(ctx context.Context, in *SendTransactionEthRequest, opts ...grpc.CallOption) (*SendTransactionEthReply, error) {
	out := new(SendTransactionEthReply)
	err := c.cc.Invoke(ctx, Transaction_SendTransactionEth_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) Transaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionReply, error) {
	out := new(TransactionReply)
	err := c.cc.Invoke(ctx, Transaction_Transaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) EthBalance(ctx context.Context, in *EthBalanceRequest, opts ...grpc.CallOption) (*EthBalanceReply, error) {
	out := new(EthBalanceReply)
	err := c.cc.Invoke(ctx, Transaction_EthBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyReply, error) {
	out := new(GenerateKeyReply)
	err := c.cc.Invoke(ctx, Transaction_GenerateKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) TokenBalance(ctx context.Context, in *TokenBalanceRequest, opts ...grpc.CallOption) (*TokenBalanceReply, error) {
	out := new(TokenBalanceReply)
	err := c.cc.Invoke(ctx, Transaction_TokenBalance_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) VerifySig(ctx context.Context, in *VerifySigRequest, opts ...grpc.CallOption) (*VerifySigReply, error) {
	out := new(VerifySigReply)
	err := c.cc.Invoke(ctx, Transaction_VerifySig_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GetReserves(ctx context.Context, in *GetReservesRequest, opts ...grpc.CallOption) (*GetReservesReply, error) {
	out := new(GetReservesReply)
	err := c.cc.Invoke(ctx, Transaction_GetReserves_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllReply, error) {
	out := new(GetAllReply)
	err := c.cc.Invoke(ctx, Transaction_GetAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GetAllTwo(ctx context.Context, in *GetAllTwoRequest, opts ...grpc.CallOption) (*GetAllTwoReply, error) {
	out := new(GetAllTwoReply)
	err := c.cc.Invoke(ctx, Transaction_GetAllTwo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GetArray(ctx context.Context, in *GetArrayRequest, opts ...grpc.CallOption) (*GetArrayReply, error) {
	out := new(GetArrayReply)
	err := c.cc.Invoke(ctx, Transaction_GetArray_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GetLpByOrderId(ctx context.Context, in *GetLpByOrderIdRequest, opts ...grpc.CallOption) (*GetLpByOrderIdReply, error) {
	out := new(GetLpByOrderIdReply)
	err := c.cc.Invoke(ctx, Transaction_GetLpByOrderId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GetBuyByOrderId(ctx context.Context, in *GetBuyByOrderIdRequest, opts ...grpc.CallOption) (*GetBuyByOrderIdReply, error) {
	out := new(GetBuyByOrderIdReply)
	err := c.cc.Invoke(ctx, Transaction_GetBuyByOrderId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GetUserLp(ctx context.Context, in *GetUserLpRequest, opts ...grpc.CallOption) (*GetUserLpReply, error) {
	out := new(GetUserLpReply)
	err := c.cc.Invoke(ctx, Transaction_GetUserLp_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GetDailyFee(ctx context.Context, in *GetDailyFeeRequest, opts ...grpc.CallOption) (*GetDailyFeeReply, error) {
	out := new(GetDailyFeeReply)
	err := c.cc.Invoke(ctx, Transaction_GetDailyFee_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) AddLiquidity(ctx context.Context, in *AddLiquidityRequest, opts ...grpc.CallOption) (*AddLiquidityReply, error) {
	out := new(AddLiquidityReply)
	err := c.cc.Invoke(ctx, Transaction_AddLiquidity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) RemoveLiquidity(ctx context.Context, in *RemoveLiquidityRequest, opts ...grpc.CallOption) (*RemoveLiquidityReply, error) {
	out := new(RemoveLiquidityReply)
	err := c.cc.Invoke(ctx, Transaction_RemoveLiquidity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) BuyAICAT(ctx context.Context, in *BuyAICATRequest, opts ...grpc.CallOption) (*BuyAICATReply, error) {
	out := new(BuyAICATReply)
	err := c.cc.Invoke(ctx, Transaction_BuyAICAT_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) WithdrawAICAT(ctx context.Context, in *WithdrawAICATRequest, opts ...grpc.CallOption) (*WithdrawAICATReply, error) {
	out := new(WithdrawAICATReply)
	err := c.cc.Invoke(ctx, Transaction_WithdrawAICAT_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) SendAICAT(ctx context.Context, in *SendAICATRequest, opts ...grpc.CallOption) (*SendAICATReply, error) {
	out := new(SendAICATReply)
	err := c.cc.Invoke(ctx, Transaction_SendAICAT_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GetBuyAICATByOrderId(ctx context.Context, in *GetBuyAICATByOrderIdRequest, opts ...grpc.CallOption) (*GetBuyAICATByOrderIdReply, error) {
	out := new(GetBuyAICATByOrderIdReply)
	err := c.cc.Invoke(ctx, Transaction_GetBuyAICATByOrderId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) AddWhite(ctx context.Context, in *AddWhiteRequest, opts ...grpc.CallOption) (*AddWhiteReply, error) {
	out := new(AddWhiteReply)
	err := c.cc.Invoke(ctx, Transaction_AddWhite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GetBoxAllLength(ctx context.Context, in *GetBoxAllRequest, opts ...grpc.CallOption) (*GetBoxAllReply, error) {
	out := new(GetBoxAllReply)
	err := c.cc.Invoke(ctx, Transaction_GetBoxAllLength_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GetBoxNew(ctx context.Context, in *GetBoxNewRequest, opts ...grpc.CallOption) (*GetBoxNewReply, error) {
	out := new(GetBoxNewReply)
	err := c.cc.Invoke(ctx, Transaction_GetBoxNew_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GetBoxOpen(ctx context.Context, in *GetBoxOpenRequest, opts ...grpc.CallOption) (*GetBoxOpenReply, error) {
	out := new(GetBoxOpenReply)
	err := c.cc.Invoke(ctx, Transaction_GetBoxOpen_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) SetReward(ctx context.Context, in *SetRewardRequest, opts ...grpc.CallOption) (*SetRewardReply, error) {
	out := new(SetRewardReply)
	err := c.cc.Invoke(ctx, Transaction_SetReward_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) SetRewardTwo(ctx context.Context, in *SetRewardRequest, opts ...grpc.CallOption) (*SetRewardReply, error) {
	out := new(SetRewardReply)
	err := c.cc.Invoke(ctx, Transaction_SetRewardTwo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionClient) GetBoxRewardEvent(ctx context.Context, in *GetBoxRewardEventRequest, opts ...grpc.CallOption) (*GetBoxRewardEventReply, error) {
	out := new(GetBoxRewardEventReply)
	err := c.cc.Invoke(ctx, Transaction_GetBoxRewardEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServer is the server API for Transaction service.
// All implementations must embed UnimplementedTransactionServer
// for forward compatibility
type TransactionServer interface {
	SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionReply, error)
	SendTransactionEth(context.Context, *SendTransactionEthRequest) (*SendTransactionEthReply, error)
	Transaction(context.Context, *TransactionRequest) (*TransactionReply, error)
	EthBalance(context.Context, *EthBalanceRequest) (*EthBalanceReply, error)
	GenerateKey(context.Context, *GenerateKeyRequest) (*GenerateKeyReply, error)
	TokenBalance(context.Context, *TokenBalanceRequest) (*TokenBalanceReply, error)
	VerifySig(context.Context, *VerifySigRequest) (*VerifySigReply, error)
	GetReserves(context.Context, *GetReservesRequest) (*GetReservesReply, error)
	GetAll(context.Context, *GetAllRequest) (*GetAllReply, error)
	GetAllTwo(context.Context, *GetAllTwoRequest) (*GetAllTwoReply, error)
	GetArray(context.Context, *GetArrayRequest) (*GetArrayReply, error)
	GetLpByOrderId(context.Context, *GetLpByOrderIdRequest) (*GetLpByOrderIdReply, error)
	GetBuyByOrderId(context.Context, *GetBuyByOrderIdRequest) (*GetBuyByOrderIdReply, error)
	GetUserLp(context.Context, *GetUserLpRequest) (*GetUserLpReply, error)
	GetDailyFee(context.Context, *GetDailyFeeRequest) (*GetDailyFeeReply, error)
	AddLiquidity(context.Context, *AddLiquidityRequest) (*AddLiquidityReply, error)
	RemoveLiquidity(context.Context, *RemoveLiquidityRequest) (*RemoveLiquidityReply, error)
	BuyAICAT(context.Context, *BuyAICATRequest) (*BuyAICATReply, error)
	WithdrawAICAT(context.Context, *WithdrawAICATRequest) (*WithdrawAICATReply, error)
	SendAICAT(context.Context, *SendAICATRequest) (*SendAICATReply, error)
	GetBuyAICATByOrderId(context.Context, *GetBuyAICATByOrderIdRequest) (*GetBuyAICATByOrderIdReply, error)
	AddWhite(context.Context, *AddWhiteRequest) (*AddWhiteReply, error)
	GetBoxAllLength(context.Context, *GetBoxAllRequest) (*GetBoxAllReply, error)
	GetBoxNew(context.Context, *GetBoxNewRequest) (*GetBoxNewReply, error)
	GetBoxOpen(context.Context, *GetBoxOpenRequest) (*GetBoxOpenReply, error)
	SetReward(context.Context, *SetRewardRequest) (*SetRewardReply, error)
	SetRewardTwo(context.Context, *SetRewardRequest) (*SetRewardReply, error)
	GetBoxRewardEvent(context.Context, *GetBoxRewardEventRequest) (*GetBoxRewardEventReply, error)
	mustEmbedUnimplementedTransactionServer()
}

// UnimplementedTransactionServer must be embedded to have forward compatible implementations.
type UnimplementedTransactionServer struct {
}

func (UnimplementedTransactionServer) SendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransaction not implemented")
}
func (UnimplementedTransactionServer) SendTransactionEth(context.Context, *SendTransactionEthRequest) (*SendTransactionEthReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransactionEth not implemented")
}
func (UnimplementedTransactionServer) Transaction(context.Context, *TransactionRequest) (*TransactionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transaction not implemented")
}
func (UnimplementedTransactionServer) EthBalance(context.Context, *EthBalanceRequest) (*EthBalanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EthBalance not implemented")
}
func (UnimplementedTransactionServer) GenerateKey(context.Context, *GenerateKeyRequest) (*GenerateKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateKey not implemented")
}
func (UnimplementedTransactionServer) TokenBalance(context.Context, *TokenBalanceRequest) (*TokenBalanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenBalance not implemented")
}
func (UnimplementedTransactionServer) VerifySig(context.Context, *VerifySigRequest) (*VerifySigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifySig not implemented")
}
func (UnimplementedTransactionServer) GetReserves(context.Context, *GetReservesRequest) (*GetReservesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReserves not implemented")
}
func (UnimplementedTransactionServer) GetAll(context.Context, *GetAllRequest) (*GetAllReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedTransactionServer) GetAllTwo(context.Context, *GetAllTwoRequest) (*GetAllTwoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTwo not implemented")
}
func (UnimplementedTransactionServer) GetArray(context.Context, *GetArrayRequest) (*GetArrayReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArray not implemented")
}
func (UnimplementedTransactionServer) GetLpByOrderId(context.Context, *GetLpByOrderIdRequest) (*GetLpByOrderIdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLpByOrderId not implemented")
}
func (UnimplementedTransactionServer) GetBuyByOrderId(context.Context, *GetBuyByOrderIdRequest) (*GetBuyByOrderIdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuyByOrderId not implemented")
}
func (UnimplementedTransactionServer) GetUserLp(context.Context, *GetUserLpRequest) (*GetUserLpReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLp not implemented")
}
func (UnimplementedTransactionServer) GetDailyFee(context.Context, *GetDailyFeeRequest) (*GetDailyFeeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyFee not implemented")
}
func (UnimplementedTransactionServer) AddLiquidity(context.Context, *AddLiquidityRequest) (*AddLiquidityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLiquidity not implemented")
}
func (UnimplementedTransactionServer) RemoveLiquidity(context.Context, *RemoveLiquidityRequest) (*RemoveLiquidityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveLiquidity not implemented")
}
func (UnimplementedTransactionServer) BuyAICAT(context.Context, *BuyAICATRequest) (*BuyAICATReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyAICAT not implemented")
}
func (UnimplementedTransactionServer) WithdrawAICAT(context.Context, *WithdrawAICATRequest) (*WithdrawAICATReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawAICAT not implemented")
}
func (UnimplementedTransactionServer) SendAICAT(context.Context, *SendAICATRequest) (*SendAICATReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAICAT not implemented")
}
func (UnimplementedTransactionServer) GetBuyAICATByOrderId(context.Context, *GetBuyAICATByOrderIdRequest) (*GetBuyAICATByOrderIdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuyAICATByOrderId not implemented")
}
func (UnimplementedTransactionServer) AddWhite(context.Context, *AddWhiteRequest) (*AddWhiteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWhite not implemented")
}
func (UnimplementedTransactionServer) GetBoxAllLength(context.Context, *GetBoxAllRequest) (*GetBoxAllReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBoxAllLength not implemented")
}
func (UnimplementedTransactionServer) GetBoxNew(context.Context, *GetBoxNewRequest) (*GetBoxNewReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBoxNew not implemented")
}
func (UnimplementedTransactionServer) GetBoxOpen(context.Context, *GetBoxOpenRequest) (*GetBoxOpenReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBoxOpen not implemented")
}
func (UnimplementedTransactionServer) SetReward(context.Context, *SetRewardRequest) (*SetRewardReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetReward not implemented")
}
func (UnimplementedTransactionServer) SetRewardTwo(context.Context, *SetRewardRequest) (*SetRewardReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRewardTwo not implemented")
}
func (UnimplementedTransactionServer) GetBoxRewardEvent(context.Context, *GetBoxRewardEventRequest) (*GetBoxRewardEventReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBoxRewardEvent not implemented")
}
func (UnimplementedTransactionServer) mustEmbedUnimplementedTransactionServer() {}

// UnsafeTransactionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionServer will
// result in compilation errors.
type UnsafeTransactionServer interface {
	mustEmbedUnimplementedTransactionServer()
}

func RegisterTransactionServer(s grpc.ServiceRegistrar, srv TransactionServer) {
	s.RegisterService(&Transaction_ServiceDesc, srv)
}

func _Transaction_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_SendTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).SendTransaction(ctx, req.(*SendTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_SendTransactionEth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionEthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).SendTransactionEth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_SendTransactionEth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).SendTransactionEth(ctx, req.(*SendTransactionEthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_Transaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).Transaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_Transaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).Transaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_EthBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EthBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).EthBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_EthBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).EthBalance(ctx, req.(*EthBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GenerateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GenerateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_GenerateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GenerateKey(ctx, req.(*GenerateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_TokenBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).TokenBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_TokenBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).TokenBalance(ctx, req.(*TokenBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_VerifySig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).VerifySig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_VerifySig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).VerifySig(ctx, req.(*VerifySigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GetReserves_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReservesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetReserves(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_GetReserves_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetReserves(ctx, req.(*GetReservesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GetAllTwo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTwoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetAllTwo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_GetAllTwo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetAllTwo(ctx, req.(*GetAllTwoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GetArray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArrayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetArray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_GetArray_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetArray(ctx, req.(*GetArrayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GetLpByOrderId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLpByOrderIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetLpByOrderId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_GetLpByOrderId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetLpByOrderId(ctx, req.(*GetLpByOrderIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GetBuyByOrderId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuyByOrderIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetBuyByOrderId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_GetBuyByOrderId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetBuyByOrderId(ctx, req.(*GetBuyByOrderIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GetUserLp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetUserLp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_GetUserLp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetUserLp(ctx, req.(*GetUserLpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GetDailyFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetDailyFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_GetDailyFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetDailyFee(ctx, req.(*GetDailyFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_AddLiquidity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLiquidityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).AddLiquidity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_AddLiquidity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).AddLiquidity(ctx, req.(*AddLiquidityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_RemoveLiquidity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLiquidityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).RemoveLiquidity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_RemoveLiquidity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).RemoveLiquidity(ctx, req.(*RemoveLiquidityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_BuyAICAT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyAICATRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).BuyAICAT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_BuyAICAT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).BuyAICAT(ctx, req.(*BuyAICATRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_WithdrawAICAT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawAICATRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).WithdrawAICAT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_WithdrawAICAT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).WithdrawAICAT(ctx, req.(*WithdrawAICATRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_SendAICAT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAICATRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).SendAICAT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_SendAICAT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).SendAICAT(ctx, req.(*SendAICATRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GetBuyAICATByOrderId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuyAICATByOrderIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetBuyAICATByOrderId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_GetBuyAICATByOrderId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetBuyAICATByOrderId(ctx, req.(*GetBuyAICATByOrderIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_AddWhite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWhiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).AddWhite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_AddWhite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).AddWhite(ctx, req.(*AddWhiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GetBoxAllLength_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoxAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetBoxAllLength(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_GetBoxAllLength_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetBoxAllLength(ctx, req.(*GetBoxAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GetBoxNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoxNewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetBoxNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_GetBoxNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetBoxNew(ctx, req.(*GetBoxNewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GetBoxOpen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoxOpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetBoxOpen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_GetBoxOpen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetBoxOpen(ctx, req.(*GetBoxOpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_SetReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).SetReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_SetReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).SetReward(ctx, req.(*SetRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_SetRewardTwo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).SetRewardTwo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_SetRewardTwo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).SetRewardTwo(ctx, req.(*SetRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transaction_GetBoxRewardEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoxRewardEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServer).GetBoxRewardEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transaction_GetBoxRewardEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServer).GetBoxRewardEvent(ctx, req.(*GetBoxRewardEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Transaction_ServiceDesc is the grpc.ServiceDesc for Transaction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transaction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.requestEth.v1.Transaction",
	HandlerType: (*TransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTransaction",
			Handler:    _Transaction_SendTransaction_Handler,
		},
		{
			MethodName: "SendTransactionEth",
			Handler:    _Transaction_SendTransactionEth_Handler,
		},
		{
			MethodName: "Transaction",
			Handler:    _Transaction_Transaction_Handler,
		},
		{
			MethodName: "EthBalance",
			Handler:    _Transaction_EthBalance_Handler,
		},
		{
			MethodName: "GenerateKey",
			Handler:    _Transaction_GenerateKey_Handler,
		},
		{
			MethodName: "TokenBalance",
			Handler:    _Transaction_TokenBalance_Handler,
		},
		{
			MethodName: "VerifySig",
			Handler:    _Transaction_VerifySig_Handler,
		},
		{
			MethodName: "GetReserves",
			Handler:    _Transaction_GetReserves_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _Transaction_GetAll_Handler,
		},
		{
			MethodName: "GetAllTwo",
			Handler:    _Transaction_GetAllTwo_Handler,
		},
		{
			MethodName: "GetArray",
			Handler:    _Transaction_GetArray_Handler,
		},
		{
			MethodName: "GetLpByOrderId",
			Handler:    _Transaction_GetLpByOrderId_Handler,
		},
		{
			MethodName: "GetBuyByOrderId",
			Handler:    _Transaction_GetBuyByOrderId_Handler,
		},
		{
			MethodName: "GetUserLp",
			Handler:    _Transaction_GetUserLp_Handler,
		},
		{
			MethodName: "GetDailyFee",
			Handler:    _Transaction_GetDailyFee_Handler,
		},
		{
			MethodName: "AddLiquidity",
			Handler:    _Transaction_AddLiquidity_Handler,
		},
		{
			MethodName: "RemoveLiquidity",
			Handler:    _Transaction_RemoveLiquidity_Handler,
		},
		{
			MethodName: "BuyAICAT",
			Handler:    _Transaction_BuyAICAT_Handler,
		},
		{
			MethodName: "WithdrawAICAT",
			Handler:    _Transaction_WithdrawAICAT_Handler,
		},
		{
			MethodName: "SendAICAT",
			Handler:    _Transaction_SendAICAT_Handler,
		},
		{
			MethodName: "GetBuyAICATByOrderId",
			Handler:    _Transaction_GetBuyAICATByOrderId_Handler,
		},
		{
			MethodName: "AddWhite",
			Handler:    _Transaction_AddWhite_Handler,
		},
		{
			MethodName: "GetBoxAllLength",
			Handler:    _Transaction_GetBoxAllLength_Handler,
		},
		{
			MethodName: "GetBoxNew",
			Handler:    _Transaction_GetBoxNew_Handler,
		},
		{
			MethodName: "GetBoxOpen",
			Handler:    _Transaction_GetBoxOpen_Handler,
		},
		{
			MethodName: "SetReward",
			Handler:    _Transaction_SetReward_Handler,
		},
		{
			MethodName: "SetRewardTwo",
			Handler:    _Transaction_SetRewardTwo_Handler,
		},
		{
			MethodName: "GetBoxRewardEvent",
			Handler:    _Transaction_GetBoxRewardEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/requestEth/v1/transaction.proto",
}
